// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cl.proto

#ifndef PROTOBUF_cl_2eproto__INCLUDED
#define PROTOBUF_cl_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace client_loginserver {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_cl_2eproto();
void protobuf_AssignDesc_cl_2eproto();
void protobuf_ShutdownFile_cl_2eproto();

class Hello;
class HelloCB;
class Login;
class LoginFailed;
class LoginSuccessfully;

// ===================================================================

class Hello : public ::google::protobuf::Message {
 public:
  Hello();
  virtual ~Hello();

  Hello(const Hello& from);

  inline Hello& operator=(const Hello& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Hello& default_instance();

  void Swap(Hello* other);

  // implements Message ----------------------------------------------

  Hello* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Hello& from);
  void MergeFrom(const Hello& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 version = 1;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::uint32 version() const;
  inline void set_version(::google::protobuf::uint32 value);

  // optional string extraData = 2;
  inline bool has_extradata() const;
  inline void clear_extradata();
  static const int kExtraDataFieldNumber = 2;
  inline const ::std::string& extradata() const;
  inline void set_extradata(const ::std::string& value);
  inline void set_extradata(const char* value);
  inline void set_extradata(const char* value, size_t size);
  inline ::std::string* mutable_extradata();
  inline ::std::string* release_extradata();
  inline void set_allocated_extradata(::std::string* extradata);

  // @@protoc_insertion_point(class_scope:client_loginserver.Hello)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_extradata();
  inline void clear_has_extradata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* extradata_;
  ::google::protobuf::uint32 version_;
  friend void  protobuf_AddDesc_cl_2eproto();
  friend void protobuf_AssignDesc_cl_2eproto();
  friend void protobuf_ShutdownFile_cl_2eproto();

  void InitAsDefaultInstance();
  static Hello* default_instance_;
};
// -------------------------------------------------------------------

class HelloCB : public ::google::protobuf::Message {
 public:
  HelloCB();
  virtual ~HelloCB();

  HelloCB(const HelloCB& from);

  inline HelloCB& operator=(const HelloCB& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HelloCB& default_instance();

  void Swap(HelloCB* other);

  // implements Message ----------------------------------------------

  HelloCB* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HelloCB& from);
  void MergeFrom(const HelloCB& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::uint32 result() const;
  inline void set_result(::google::protobuf::uint32 value);

  // optional uint32 version = 2;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 2;
  inline ::google::protobuf::uint32 version() const;
  inline void set_version(::google::protobuf::uint32 value);

  // optional string extraData = 3;
  inline bool has_extradata() const;
  inline void clear_extradata();
  static const int kExtraDataFieldNumber = 3;
  inline const ::std::string& extradata() const;
  inline void set_extradata(const ::std::string& value);
  inline void set_extradata(const char* value);
  inline void set_extradata(const char* value, size_t size);
  inline ::std::string* mutable_extradata();
  inline ::std::string* release_extradata();
  inline void set_allocated_extradata(::std::string* extradata);

  // @@protoc_insertion_point(class_scope:client_loginserver.HelloCB)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_extradata();
  inline void clear_has_extradata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 result_;
  ::google::protobuf::uint32 version_;
  ::std::string* extradata_;
  friend void  protobuf_AddDesc_cl_2eproto();
  friend void protobuf_AssignDesc_cl_2eproto();
  friend void protobuf_ShutdownFile_cl_2eproto();

  void InitAsDefaultInstance();
  static HelloCB* default_instance_;
};
// -------------------------------------------------------------------

class Login : public ::google::protobuf::Message {
 public:
  Login();
  virtual ~Login();

  Login(const Login& from);

  inline Login& operator=(const Login& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Login& default_instance();

  void Swap(Login* other);

  // implements Message ----------------------------------------------

  Login* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Login& from);
  void MergeFrom(const Login& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 ctype = 1;
  inline bool has_ctype() const;
  inline void clear_ctype();
  static const int kCtypeFieldNumber = 1;
  inline ::google::protobuf::uint32 ctype() const;
  inline void set_ctype(::google::protobuf::uint32 value);

  // optional string account = 2;
  inline bool has_account() const;
  inline void clear_account();
  static const int kAccountFieldNumber = 2;
  inline const ::std::string& account() const;
  inline void set_account(const ::std::string& value);
  inline void set_account(const char* value);
  inline void set_account(const char* value, size_t size);
  inline ::std::string* mutable_account();
  inline ::std::string* release_account();
  inline void set_allocated_account(::std::string* account);

  // optional string password = 3;
  inline bool has_password() const;
  inline void clear_password();
  static const int kPasswordFieldNumber = 3;
  inline const ::std::string& password() const;
  inline void set_password(const ::std::string& value);
  inline void set_password(const char* value);
  inline void set_password(const char* value, size_t size);
  inline ::std::string* mutable_password();
  inline ::std::string* release_password();
  inline void set_allocated_password(::std::string* password);

  // optional string extraData = 4;
  inline bool has_extradata() const;
  inline void clear_extradata();
  static const int kExtraDataFieldNumber = 4;
  inline const ::std::string& extradata() const;
  inline void set_extradata(const ::std::string& value);
  inline void set_extradata(const char* value);
  inline void set_extradata(const char* value, size_t size);
  inline ::std::string* mutable_extradata();
  inline ::std::string* release_extradata();
  inline void set_allocated_extradata(::std::string* extradata);

  // @@protoc_insertion_point(class_scope:client_loginserver.Login)
 private:
  inline void set_has_ctype();
  inline void clear_has_ctype();
  inline void set_has_account();
  inline void clear_has_account();
  inline void set_has_password();
  inline void clear_has_password();
  inline void set_has_extradata();
  inline void clear_has_extradata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* account_;
  ::std::string* password_;
  ::std::string* extradata_;
  ::google::protobuf::uint32 ctype_;
  friend void  protobuf_AddDesc_cl_2eproto();
  friend void protobuf_AssignDesc_cl_2eproto();
  friend void protobuf_ShutdownFile_cl_2eproto();

  void InitAsDefaultInstance();
  static Login* default_instance_;
};
// -------------------------------------------------------------------

class LoginFailed : public ::google::protobuf::Message {
 public:
  LoginFailed();
  virtual ~LoginFailed();

  LoginFailed(const LoginFailed& from);

  inline LoginFailed& operator=(const LoginFailed& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginFailed& default_instance();

  void Swap(LoginFailed* other);

  // implements Message ----------------------------------------------

  LoginFailed* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginFailed& from);
  void MergeFrom(const LoginFailed& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 failedcode = 1;
  inline bool has_failedcode() const;
  inline void clear_failedcode();
  static const int kFailedcodeFieldNumber = 1;
  inline ::google::protobuf::uint32 failedcode() const;
  inline void set_failedcode(::google::protobuf::uint32 value);

  // optional string extraData = 2;
  inline bool has_extradata() const;
  inline void clear_extradata();
  static const int kExtraDataFieldNumber = 2;
  inline const ::std::string& extradata() const;
  inline void set_extradata(const ::std::string& value);
  inline void set_extradata(const char* value);
  inline void set_extradata(const char* value, size_t size);
  inline ::std::string* mutable_extradata();
  inline ::std::string* release_extradata();
  inline void set_allocated_extradata(::std::string* extradata);

  // @@protoc_insertion_point(class_scope:client_loginserver.LoginFailed)
 private:
  inline void set_has_failedcode();
  inline void clear_has_failedcode();
  inline void set_has_extradata();
  inline void clear_has_extradata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* extradata_;
  ::google::protobuf::uint32 failedcode_;
  friend void  protobuf_AddDesc_cl_2eproto();
  friend void protobuf_AssignDesc_cl_2eproto();
  friend void protobuf_ShutdownFile_cl_2eproto();

  void InitAsDefaultInstance();
  static LoginFailed* default_instance_;
};
// -------------------------------------------------------------------

class LoginSuccessfully : public ::google::protobuf::Message {
 public:
  LoginSuccessfully();
  virtual ~LoginSuccessfully();

  LoginSuccessfully(const LoginSuccessfully& from);

  inline LoginSuccessfully& operator=(const LoginSuccessfully& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginSuccessfully& default_instance();

  void Swap(LoginSuccessfully* other);

  // implements Message ----------------------------------------------

  LoginSuccessfully* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginSuccessfully& from);
  void MergeFrom(const LoginSuccessfully& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string accountName = 1;
  inline bool has_accountname() const;
  inline void clear_accountname();
  static const int kAccountNameFieldNumber = 1;
  inline const ::std::string& accountname() const;
  inline void set_accountname(const ::std::string& value);
  inline void set_accountname(const char* value);
  inline void set_accountname(const char* value, size_t size);
  inline ::std::string* mutable_accountname();
  inline ::std::string* release_accountname();
  inline void set_allocated_accountname(::std::string* accountname);

  // optional string baseIp = 2;
  inline bool has_baseip() const;
  inline void clear_baseip();
  static const int kBaseIpFieldNumber = 2;
  inline const ::std::string& baseip() const;
  inline void set_baseip(const ::std::string& value);
  inline void set_baseip(const char* value);
  inline void set_baseip(const char* value, size_t size);
  inline ::std::string* mutable_baseip();
  inline ::std::string* release_baseip();
  inline void set_allocated_baseip(::std::string* baseip);

  // optional uint32 basePort = 3;
  inline bool has_baseport() const;
  inline void clear_baseport();
  static const int kBasePortFieldNumber = 3;
  inline ::google::protobuf::uint32 baseport() const;
  inline void set_baseport(::google::protobuf::uint32 value);

  // optional string extraData = 4;
  inline bool has_extradata() const;
  inline void clear_extradata();
  static const int kExtraDataFieldNumber = 4;
  inline const ::std::string& extradata() const;
  inline void set_extradata(const ::std::string& value);
  inline void set_extradata(const char* value);
  inline void set_extradata(const char* value, size_t size);
  inline ::std::string* mutable_extradata();
  inline ::std::string* release_extradata();
  inline void set_allocated_extradata(::std::string* extradata);

  // @@protoc_insertion_point(class_scope:client_loginserver.LoginSuccessfully)
 private:
  inline void set_has_accountname();
  inline void clear_has_accountname();
  inline void set_has_baseip();
  inline void clear_has_baseip();
  inline void set_has_baseport();
  inline void clear_has_baseport();
  inline void set_has_extradata();
  inline void clear_has_extradata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* accountname_;
  ::std::string* baseip_;
  ::std::string* extradata_;
  ::google::protobuf::uint32 baseport_;
  friend void  protobuf_AddDesc_cl_2eproto();
  friend void protobuf_AssignDesc_cl_2eproto();
  friend void protobuf_ShutdownFile_cl_2eproto();

  void InitAsDefaultInstance();
  static LoginSuccessfully* default_instance_;
};
// ===================================================================


// ===================================================================

// Hello

// optional uint32 version = 1;
inline bool Hello::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Hello::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Hello::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Hello::clear_version() {
  version_ = 0u;
  clear_has_version();
}
inline ::google::protobuf::uint32 Hello::version() const {
  // @@protoc_insertion_point(field_get:client_loginserver.Hello.version)
  return version_;
}
inline void Hello::set_version(::google::protobuf::uint32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:client_loginserver.Hello.version)
}

// optional string extraData = 2;
inline bool Hello::has_extradata() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Hello::set_has_extradata() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Hello::clear_has_extradata() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Hello::clear_extradata() {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_->clear();
  }
  clear_has_extradata();
}
inline const ::std::string& Hello::extradata() const {
  // @@protoc_insertion_point(field_get:client_loginserver.Hello.extraData)
  return *extradata_;
}
inline void Hello::set_extradata(const ::std::string& value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set:client_loginserver.Hello.extraData)
}
inline void Hello::set_extradata(const char* value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set_char:client_loginserver.Hello.extraData)
}
inline void Hello::set_extradata(const char* value, size_t size) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:client_loginserver.Hello.extraData)
}
inline ::std::string* Hello::mutable_extradata() {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:client_loginserver.Hello.extraData)
  return extradata_;
}
inline ::std::string* Hello::release_extradata() {
  clear_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = extradata_;
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Hello::set_allocated_extradata(::std::string* extradata) {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extradata_;
  }
  if (extradata) {
    set_has_extradata();
    extradata_ = extradata;
  } else {
    clear_has_extradata();
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:client_loginserver.Hello.extraData)
}

// -------------------------------------------------------------------

// HelloCB

// optional uint32 result = 1;
inline bool HelloCB::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HelloCB::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HelloCB::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HelloCB::clear_result() {
  result_ = 0u;
  clear_has_result();
}
inline ::google::protobuf::uint32 HelloCB::result() const {
  // @@protoc_insertion_point(field_get:client_loginserver.HelloCB.result)
  return result_;
}
inline void HelloCB::set_result(::google::protobuf::uint32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:client_loginserver.HelloCB.result)
}

// optional uint32 version = 2;
inline bool HelloCB::has_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HelloCB::set_has_version() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HelloCB::clear_has_version() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HelloCB::clear_version() {
  version_ = 0u;
  clear_has_version();
}
inline ::google::protobuf::uint32 HelloCB::version() const {
  // @@protoc_insertion_point(field_get:client_loginserver.HelloCB.version)
  return version_;
}
inline void HelloCB::set_version(::google::protobuf::uint32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:client_loginserver.HelloCB.version)
}

// optional string extraData = 3;
inline bool HelloCB::has_extradata() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HelloCB::set_has_extradata() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HelloCB::clear_has_extradata() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HelloCB::clear_extradata() {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_->clear();
  }
  clear_has_extradata();
}
inline const ::std::string& HelloCB::extradata() const {
  // @@protoc_insertion_point(field_get:client_loginserver.HelloCB.extraData)
  return *extradata_;
}
inline void HelloCB::set_extradata(const ::std::string& value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set:client_loginserver.HelloCB.extraData)
}
inline void HelloCB::set_extradata(const char* value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set_char:client_loginserver.HelloCB.extraData)
}
inline void HelloCB::set_extradata(const char* value, size_t size) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:client_loginserver.HelloCB.extraData)
}
inline ::std::string* HelloCB::mutable_extradata() {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:client_loginserver.HelloCB.extraData)
  return extradata_;
}
inline ::std::string* HelloCB::release_extradata() {
  clear_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = extradata_;
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void HelloCB::set_allocated_extradata(::std::string* extradata) {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extradata_;
  }
  if (extradata) {
    set_has_extradata();
    extradata_ = extradata;
  } else {
    clear_has_extradata();
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:client_loginserver.HelloCB.extraData)
}

// -------------------------------------------------------------------

// Login

// optional uint32 ctype = 1;
inline bool Login::has_ctype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Login::set_has_ctype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Login::clear_has_ctype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Login::clear_ctype() {
  ctype_ = 0u;
  clear_has_ctype();
}
inline ::google::protobuf::uint32 Login::ctype() const {
  // @@protoc_insertion_point(field_get:client_loginserver.Login.ctype)
  return ctype_;
}
inline void Login::set_ctype(::google::protobuf::uint32 value) {
  set_has_ctype();
  ctype_ = value;
  // @@protoc_insertion_point(field_set:client_loginserver.Login.ctype)
}

// optional string account = 2;
inline bool Login::has_account() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Login::set_has_account() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Login::clear_has_account() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Login::clear_account() {
  if (account_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    account_->clear();
  }
  clear_has_account();
}
inline const ::std::string& Login::account() const {
  // @@protoc_insertion_point(field_get:client_loginserver.Login.account)
  return *account_;
}
inline void Login::set_account(const ::std::string& value) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    account_ = new ::std::string;
  }
  account_->assign(value);
  // @@protoc_insertion_point(field_set:client_loginserver.Login.account)
}
inline void Login::set_account(const char* value) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    account_ = new ::std::string;
  }
  account_->assign(value);
  // @@protoc_insertion_point(field_set_char:client_loginserver.Login.account)
}
inline void Login::set_account(const char* value, size_t size) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    account_ = new ::std::string;
  }
  account_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:client_loginserver.Login.account)
}
inline ::std::string* Login::mutable_account() {
  set_has_account();
  if (account_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    account_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:client_loginserver.Login.account)
  return account_;
}
inline ::std::string* Login::release_account() {
  clear_has_account();
  if (account_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = account_;
    account_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Login::set_allocated_account(::std::string* account) {
  if (account_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete account_;
  }
  if (account) {
    set_has_account();
    account_ = account;
  } else {
    clear_has_account();
    account_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:client_loginserver.Login.account)
}

// optional string password = 3;
inline bool Login::has_password() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Login::set_has_password() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Login::clear_has_password() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Login::clear_password() {
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_->clear();
  }
  clear_has_password();
}
inline const ::std::string& Login::password() const {
  // @@protoc_insertion_point(field_get:client_loginserver.Login.password)
  return *password_;
}
inline void Login::set_password(const ::std::string& value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(value);
  // @@protoc_insertion_point(field_set:client_loginserver.Login.password)
}
inline void Login::set_password(const char* value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(value);
  // @@protoc_insertion_point(field_set_char:client_loginserver.Login.password)
}
inline void Login::set_password(const char* value, size_t size) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:client_loginserver.Login.password)
}
inline ::std::string* Login::mutable_password() {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:client_loginserver.Login.password)
  return password_;
}
inline ::std::string* Login::release_password() {
  clear_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = password_;
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Login::set_allocated_password(::std::string* password) {
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete password_;
  }
  if (password) {
    set_has_password();
    password_ = password;
  } else {
    clear_has_password();
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:client_loginserver.Login.password)
}

// optional string extraData = 4;
inline bool Login::has_extradata() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Login::set_has_extradata() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Login::clear_has_extradata() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Login::clear_extradata() {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_->clear();
  }
  clear_has_extradata();
}
inline const ::std::string& Login::extradata() const {
  // @@protoc_insertion_point(field_get:client_loginserver.Login.extraData)
  return *extradata_;
}
inline void Login::set_extradata(const ::std::string& value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set:client_loginserver.Login.extraData)
}
inline void Login::set_extradata(const char* value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set_char:client_loginserver.Login.extraData)
}
inline void Login::set_extradata(const char* value, size_t size) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:client_loginserver.Login.extraData)
}
inline ::std::string* Login::mutable_extradata() {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:client_loginserver.Login.extraData)
  return extradata_;
}
inline ::std::string* Login::release_extradata() {
  clear_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = extradata_;
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Login::set_allocated_extradata(::std::string* extradata) {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extradata_;
  }
  if (extradata) {
    set_has_extradata();
    extradata_ = extradata;
  } else {
    clear_has_extradata();
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:client_loginserver.Login.extraData)
}

// -------------------------------------------------------------------

// LoginFailed

// optional uint32 failedcode = 1;
inline bool LoginFailed::has_failedcode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginFailed::set_has_failedcode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginFailed::clear_has_failedcode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginFailed::clear_failedcode() {
  failedcode_ = 0u;
  clear_has_failedcode();
}
inline ::google::protobuf::uint32 LoginFailed::failedcode() const {
  // @@protoc_insertion_point(field_get:client_loginserver.LoginFailed.failedcode)
  return failedcode_;
}
inline void LoginFailed::set_failedcode(::google::protobuf::uint32 value) {
  set_has_failedcode();
  failedcode_ = value;
  // @@protoc_insertion_point(field_set:client_loginserver.LoginFailed.failedcode)
}

// optional string extraData = 2;
inline bool LoginFailed::has_extradata() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginFailed::set_has_extradata() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginFailed::clear_has_extradata() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginFailed::clear_extradata() {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_->clear();
  }
  clear_has_extradata();
}
inline const ::std::string& LoginFailed::extradata() const {
  // @@protoc_insertion_point(field_get:client_loginserver.LoginFailed.extraData)
  return *extradata_;
}
inline void LoginFailed::set_extradata(const ::std::string& value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set:client_loginserver.LoginFailed.extraData)
}
inline void LoginFailed::set_extradata(const char* value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set_char:client_loginserver.LoginFailed.extraData)
}
inline void LoginFailed::set_extradata(const char* value, size_t size) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:client_loginserver.LoginFailed.extraData)
}
inline ::std::string* LoginFailed::mutable_extradata() {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:client_loginserver.LoginFailed.extraData)
  return extradata_;
}
inline ::std::string* LoginFailed::release_extradata() {
  clear_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = extradata_;
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LoginFailed::set_allocated_extradata(::std::string* extradata) {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extradata_;
  }
  if (extradata) {
    set_has_extradata();
    extradata_ = extradata;
  } else {
    clear_has_extradata();
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:client_loginserver.LoginFailed.extraData)
}

// -------------------------------------------------------------------

// LoginSuccessfully

// optional string accountName = 1;
inline bool LoginSuccessfully::has_accountname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginSuccessfully::set_has_accountname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginSuccessfully::clear_has_accountname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginSuccessfully::clear_accountname() {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_->clear();
  }
  clear_has_accountname();
}
inline const ::std::string& LoginSuccessfully::accountname() const {
  // @@protoc_insertion_point(field_get:client_loginserver.LoginSuccessfully.accountName)
  return *accountname_;
}
inline void LoginSuccessfully::set_accountname(const ::std::string& value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set:client_loginserver.LoginSuccessfully.accountName)
}
inline void LoginSuccessfully::set_accountname(const char* value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set_char:client_loginserver.LoginSuccessfully.accountName)
}
inline void LoginSuccessfully::set_accountname(const char* value, size_t size) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:client_loginserver.LoginSuccessfully.accountName)
}
inline ::std::string* LoginSuccessfully::mutable_accountname() {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:client_loginserver.LoginSuccessfully.accountName)
  return accountname_;
}
inline ::std::string* LoginSuccessfully::release_accountname() {
  clear_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = accountname_;
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LoginSuccessfully::set_allocated_accountname(::std::string* accountname) {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete accountname_;
  }
  if (accountname) {
    set_has_accountname();
    accountname_ = accountname;
  } else {
    clear_has_accountname();
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:client_loginserver.LoginSuccessfully.accountName)
}

// optional string baseIp = 2;
inline bool LoginSuccessfully::has_baseip() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginSuccessfully::set_has_baseip() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginSuccessfully::clear_has_baseip() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginSuccessfully::clear_baseip() {
  if (baseip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    baseip_->clear();
  }
  clear_has_baseip();
}
inline const ::std::string& LoginSuccessfully::baseip() const {
  // @@protoc_insertion_point(field_get:client_loginserver.LoginSuccessfully.baseIp)
  return *baseip_;
}
inline void LoginSuccessfully::set_baseip(const ::std::string& value) {
  set_has_baseip();
  if (baseip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    baseip_ = new ::std::string;
  }
  baseip_->assign(value);
  // @@protoc_insertion_point(field_set:client_loginserver.LoginSuccessfully.baseIp)
}
inline void LoginSuccessfully::set_baseip(const char* value) {
  set_has_baseip();
  if (baseip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    baseip_ = new ::std::string;
  }
  baseip_->assign(value);
  // @@protoc_insertion_point(field_set_char:client_loginserver.LoginSuccessfully.baseIp)
}
inline void LoginSuccessfully::set_baseip(const char* value, size_t size) {
  set_has_baseip();
  if (baseip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    baseip_ = new ::std::string;
  }
  baseip_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:client_loginserver.LoginSuccessfully.baseIp)
}
inline ::std::string* LoginSuccessfully::mutable_baseip() {
  set_has_baseip();
  if (baseip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    baseip_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:client_loginserver.LoginSuccessfully.baseIp)
  return baseip_;
}
inline ::std::string* LoginSuccessfully::release_baseip() {
  clear_has_baseip();
  if (baseip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = baseip_;
    baseip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LoginSuccessfully::set_allocated_baseip(::std::string* baseip) {
  if (baseip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete baseip_;
  }
  if (baseip) {
    set_has_baseip();
    baseip_ = baseip;
  } else {
    clear_has_baseip();
    baseip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:client_loginserver.LoginSuccessfully.baseIp)
}

// optional uint32 basePort = 3;
inline bool LoginSuccessfully::has_baseport() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LoginSuccessfully::set_has_baseport() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LoginSuccessfully::clear_has_baseport() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LoginSuccessfully::clear_baseport() {
  baseport_ = 0u;
  clear_has_baseport();
}
inline ::google::protobuf::uint32 LoginSuccessfully::baseport() const {
  // @@protoc_insertion_point(field_get:client_loginserver.LoginSuccessfully.basePort)
  return baseport_;
}
inline void LoginSuccessfully::set_baseport(::google::protobuf::uint32 value) {
  set_has_baseport();
  baseport_ = value;
  // @@protoc_insertion_point(field_set:client_loginserver.LoginSuccessfully.basePort)
}

// optional string extraData = 4;
inline bool LoginSuccessfully::has_extradata() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LoginSuccessfully::set_has_extradata() {
  _has_bits_[0] |= 0x00000008u;
}
inline void LoginSuccessfully::clear_has_extradata() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void LoginSuccessfully::clear_extradata() {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_->clear();
  }
  clear_has_extradata();
}
inline const ::std::string& LoginSuccessfully::extradata() const {
  // @@protoc_insertion_point(field_get:client_loginserver.LoginSuccessfully.extraData)
  return *extradata_;
}
inline void LoginSuccessfully::set_extradata(const ::std::string& value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set:client_loginserver.LoginSuccessfully.extraData)
}
inline void LoginSuccessfully::set_extradata(const char* value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set_char:client_loginserver.LoginSuccessfully.extraData)
}
inline void LoginSuccessfully::set_extradata(const char* value, size_t size) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:client_loginserver.LoginSuccessfully.extraData)
}
inline ::std::string* LoginSuccessfully::mutable_extradata() {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:client_loginserver.LoginSuccessfully.extraData)
  return extradata_;
}
inline ::std::string* LoginSuccessfully::release_extradata() {
  clear_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = extradata_;
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LoginSuccessfully::set_allocated_extradata(::std::string* extradata) {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extradata_;
  }
  if (extradata) {
    set_has_extradata();
    extradata_ = extradata;
  } else {
    clear_has_extradata();
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:client_loginserver.LoginSuccessfully.extraData)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace client_loginserver

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cl_2eproto__INCLUDED
