// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lbm.proto

#ifndef PROTOBUF_lbm_2eproto__INCLUDED
#define PROTOBUF_lbm_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace login_basemgr {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lbm_2eproto();
void protobuf_AssignDesc_lbm_2eproto();
void protobuf_ShutdownFile_lbm_2eproto();

class RegisterPendingAccount;
class RegisterPendingAccountEx;
class LoginAccountQueryBaseappAddrFromBaseappmgr;
class BaseappInitProgress;

// ===================================================================

class RegisterPendingAccount : public ::google::protobuf::Message {
 public:
  RegisterPendingAccount();
  virtual ~RegisterPendingAccount();

  RegisterPendingAccount(const RegisterPendingAccount& from);

  inline RegisterPendingAccount& operator=(const RegisterPendingAccount& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegisterPendingAccount& default_instance();

  void Swap(RegisterPendingAccount* other);

  // implements Message ----------------------------------------------

  RegisterPendingAccount* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegisterPendingAccount& from);
  void MergeFrom(const RegisterPendingAccount& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string loginName = 1;
  inline bool has_loginname() const;
  inline void clear_loginname();
  static const int kLoginNameFieldNumber = 1;
  inline const ::std::string& loginname() const;
  inline void set_loginname(const ::std::string& value);
  inline void set_loginname(const char* value);
  inline void set_loginname(const char* value, size_t size);
  inline ::std::string* mutable_loginname();
  inline ::std::string* release_loginname();
  inline void set_allocated_loginname(::std::string* loginname);

  // optional string accountName = 2;
  inline bool has_accountname() const;
  inline void clear_accountname();
  static const int kAccountNameFieldNumber = 2;
  inline const ::std::string& accountname() const;
  inline void set_accountname(const ::std::string& value);
  inline void set_accountname(const char* value);
  inline void set_accountname(const char* value, size_t size);
  inline ::std::string* mutable_accountname();
  inline ::std::string* release_accountname();
  inline void set_allocated_accountname(::std::string* accountname);

  // optional string password = 3;
  inline bool has_password() const;
  inline void clear_password();
  static const int kPasswordFieldNumber = 3;
  inline const ::std::string& password() const;
  inline void set_password(const ::std::string& value);
  inline void set_password(const char* value);
  inline void set_password(const char* value, size_t size);
  inline ::std::string* mutable_password();
  inline ::std::string* release_password();
  inline void set_allocated_password(::std::string* password);

  // optional uint64 dbid = 4;
  inline bool has_dbid() const;
  inline void clear_dbid();
  static const int kDbidFieldNumber = 4;
  inline ::google::protobuf::uint64 dbid() const;
  inline void set_dbid(::google::protobuf::uint64 value);

  // optional uint32 flags = 5;
  inline bool has_flags() const;
  inline void clear_flags();
  static const int kFlagsFieldNumber = 5;
  inline ::google::protobuf::uint32 flags() const;
  inline void set_flags(::google::protobuf::uint32 value);

  // optional string extraData = 6;
  inline bool has_extradata() const;
  inline void clear_extradata();
  static const int kExtraDataFieldNumber = 6;
  inline const ::std::string& extradata() const;
  inline void set_extradata(const ::std::string& value);
  inline void set_extradata(const char* value);
  inline void set_extradata(const char* value, size_t size);
  inline ::std::string* mutable_extradata();
  inline ::std::string* release_extradata();
  inline void set_allocated_extradata(::std::string* extradata);

  // @@protoc_insertion_point(class_scope:login_basemgr.RegisterPendingAccount)
 private:
  inline void set_has_loginname();
  inline void clear_has_loginname();
  inline void set_has_accountname();
  inline void clear_has_accountname();
  inline void set_has_password();
  inline void clear_has_password();
  inline void set_has_dbid();
  inline void clear_has_dbid();
  inline void set_has_flags();
  inline void clear_has_flags();
  inline void set_has_extradata();
  inline void clear_has_extradata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* loginname_;
  ::std::string* accountname_;
  ::std::string* password_;
  ::google::protobuf::uint64 dbid_;
  ::std::string* extradata_;
  ::google::protobuf::uint32 flags_;
  friend void  protobuf_AddDesc_lbm_2eproto();
  friend void protobuf_AssignDesc_lbm_2eproto();
  friend void protobuf_ShutdownFile_lbm_2eproto();

  void InitAsDefaultInstance();
  static RegisterPendingAccount* default_instance_;
};
// -------------------------------------------------------------------

class RegisterPendingAccountEx : public ::google::protobuf::Message {
 public:
  RegisterPendingAccountEx();
  virtual ~RegisterPendingAccountEx();

  RegisterPendingAccountEx(const RegisterPendingAccountEx& from);

  inline RegisterPendingAccountEx& operator=(const RegisterPendingAccountEx& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegisterPendingAccountEx& default_instance();

  void Swap(RegisterPendingAccountEx* other);

  // implements Message ----------------------------------------------

  RegisterPendingAccountEx* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegisterPendingAccountEx& from);
  void MergeFrom(const RegisterPendingAccountEx& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 componentID = 1;
  inline bool has_componentid() const;
  inline void clear_componentid();
  static const int kComponentIDFieldNumber = 1;
  inline ::google::protobuf::uint64 componentid() const;
  inline void set_componentid(::google::protobuf::uint64 value);

  // optional string loginName = 2;
  inline bool has_loginname() const;
  inline void clear_loginname();
  static const int kLoginNameFieldNumber = 2;
  inline const ::std::string& loginname() const;
  inline void set_loginname(const ::std::string& value);
  inline void set_loginname(const char* value);
  inline void set_loginname(const char* value, size_t size);
  inline ::std::string* mutable_loginname();
  inline ::std::string* release_loginname();
  inline void set_allocated_loginname(::std::string* loginname);

  // optional string accountName = 3;
  inline bool has_accountname() const;
  inline void clear_accountname();
  static const int kAccountNameFieldNumber = 3;
  inline const ::std::string& accountname() const;
  inline void set_accountname(const ::std::string& value);
  inline void set_accountname(const char* value);
  inline void set_accountname(const char* value, size_t size);
  inline ::std::string* mutable_accountname();
  inline ::std::string* release_accountname();
  inline void set_allocated_accountname(::std::string* accountname);

  // optional string password = 4;
  inline bool has_password() const;
  inline void clear_password();
  static const int kPasswordFieldNumber = 4;
  inline const ::std::string& password() const;
  inline void set_password(const ::std::string& value);
  inline void set_password(const char* value);
  inline void set_password(const char* value, size_t size);
  inline ::std::string* mutable_password();
  inline ::std::string* release_password();
  inline void set_allocated_password(::std::string* password);

  // optional int32 entityID = 5;
  inline bool has_entityid() const;
  inline void clear_entityid();
  static const int kEntityIDFieldNumber = 5;
  inline ::google::protobuf::int32 entityid() const;
  inline void set_entityid(::google::protobuf::int32 value);

  // optional uint64 dbid = 6;
  inline bool has_dbid() const;
  inline void clear_dbid();
  static const int kDbidFieldNumber = 6;
  inline ::google::protobuf::uint64 dbid() const;
  inline void set_dbid(::google::protobuf::uint64 value);

  // optional uint32 flags = 7;
  inline bool has_flags() const;
  inline void clear_flags();
  static const int kFlagsFieldNumber = 7;
  inline ::google::protobuf::uint32 flags() const;
  inline void set_flags(::google::protobuf::uint32 value);

  // optional string extraData = 8;
  inline bool has_extradata() const;
  inline void clear_extradata();
  static const int kExtraDataFieldNumber = 8;
  inline const ::std::string& extradata() const;
  inline void set_extradata(const ::std::string& value);
  inline void set_extradata(const char* value);
  inline void set_extradata(const char* value, size_t size);
  inline ::std::string* mutable_extradata();
  inline ::std::string* release_extradata();
  inline void set_allocated_extradata(::std::string* extradata);

  // @@protoc_insertion_point(class_scope:login_basemgr.RegisterPendingAccountEx)
 private:
  inline void set_has_componentid();
  inline void clear_has_componentid();
  inline void set_has_loginname();
  inline void clear_has_loginname();
  inline void set_has_accountname();
  inline void clear_has_accountname();
  inline void set_has_password();
  inline void clear_has_password();
  inline void set_has_entityid();
  inline void clear_has_entityid();
  inline void set_has_dbid();
  inline void clear_has_dbid();
  inline void set_has_flags();
  inline void clear_has_flags();
  inline void set_has_extradata();
  inline void clear_has_extradata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 componentid_;
  ::std::string* loginname_;
  ::std::string* accountname_;
  ::std::string* password_;
  ::google::protobuf::uint64 dbid_;
  ::google::protobuf::int32 entityid_;
  ::google::protobuf::uint32 flags_;
  ::std::string* extradata_;
  friend void  protobuf_AddDesc_lbm_2eproto();
  friend void protobuf_AssignDesc_lbm_2eproto();
  friend void protobuf_ShutdownFile_lbm_2eproto();

  void InitAsDefaultInstance();
  static RegisterPendingAccountEx* default_instance_;
};
// -------------------------------------------------------------------

class LoginAccountQueryBaseappAddrFromBaseappmgr : public ::google::protobuf::Message {
 public:
  LoginAccountQueryBaseappAddrFromBaseappmgr();
  virtual ~LoginAccountQueryBaseappAddrFromBaseappmgr();

  LoginAccountQueryBaseappAddrFromBaseappmgr(const LoginAccountQueryBaseappAddrFromBaseappmgr& from);

  inline LoginAccountQueryBaseappAddrFromBaseappmgr& operator=(const LoginAccountQueryBaseappAddrFromBaseappmgr& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginAccountQueryBaseappAddrFromBaseappmgr& default_instance();

  void Swap(LoginAccountQueryBaseappAddrFromBaseappmgr* other);

  // implements Message ----------------------------------------------

  LoginAccountQueryBaseappAddrFromBaseappmgr* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginAccountQueryBaseappAddrFromBaseappmgr& from);
  void MergeFrom(const LoginAccountQueryBaseappAddrFromBaseappmgr& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string loginName = 1;
  inline bool has_loginname() const;
  inline void clear_loginname();
  static const int kLoginNameFieldNumber = 1;
  inline const ::std::string& loginname() const;
  inline void set_loginname(const ::std::string& value);
  inline void set_loginname(const char* value);
  inline void set_loginname(const char* value, size_t size);
  inline ::std::string* mutable_loginname();
  inline ::std::string* release_loginname();
  inline void set_allocated_loginname(::std::string* loginname);

  // optional string accountName = 2;
  inline bool has_accountname() const;
  inline void clear_accountname();
  static const int kAccountNameFieldNumber = 2;
  inline const ::std::string& accountname() const;
  inline void set_accountname(const ::std::string& value);
  inline void set_accountname(const char* value);
  inline void set_accountname(const char* value, size_t size);
  inline ::std::string* mutable_accountname();
  inline ::std::string* release_accountname();
  inline void set_allocated_accountname(::std::string* accountname);

  // optional string ip = 3;
  inline bool has_ip() const;
  inline void clear_ip();
  static const int kIpFieldNumber = 3;
  inline const ::std::string& ip() const;
  inline void set_ip(const ::std::string& value);
  inline void set_ip(const char* value);
  inline void set_ip(const char* value, size_t size);
  inline ::std::string* mutable_ip();
  inline ::std::string* release_ip();
  inline void set_allocated_ip(::std::string* ip);

  // optional uint32 port = 4;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 4;
  inline ::google::protobuf::uint32 port() const;
  inline void set_port(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr)
 private:
  inline void set_has_loginname();
  inline void clear_has_loginname();
  inline void set_has_accountname();
  inline void clear_has_accountname();
  inline void set_has_ip();
  inline void clear_has_ip();
  inline void set_has_port();
  inline void clear_has_port();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* loginname_;
  ::std::string* accountname_;
  ::std::string* ip_;
  ::google::protobuf::uint32 port_;
  friend void  protobuf_AddDesc_lbm_2eproto();
  friend void protobuf_AssignDesc_lbm_2eproto();
  friend void protobuf_ShutdownFile_lbm_2eproto();

  void InitAsDefaultInstance();
  static LoginAccountQueryBaseappAddrFromBaseappmgr* default_instance_;
};
// -------------------------------------------------------------------

class BaseappInitProgress : public ::google::protobuf::Message {
 public:
  BaseappInitProgress();
  virtual ~BaseappInitProgress();

  BaseappInitProgress(const BaseappInitProgress& from);

  inline BaseappInitProgress& operator=(const BaseappInitProgress& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BaseappInitProgress& default_instance();

  void Swap(BaseappInitProgress* other);

  // implements Message ----------------------------------------------

  BaseappInitProgress* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BaseappInitProgress& from);
  void MergeFrom(const BaseappInitProgress& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 baseappsInitProgress = 1;
  inline bool has_baseappsinitprogress() const;
  inline void clear_baseappsinitprogress();
  static const int kBaseappsInitProgressFieldNumber = 1;
  inline ::google::protobuf::uint32 baseappsinitprogress() const;
  inline void set_baseappsinitprogress(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:login_basemgr.BaseappInitProgress)
 private:
  inline void set_has_baseappsinitprogress();
  inline void clear_has_baseappsinitprogress();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 baseappsinitprogress_;
  friend void  protobuf_AddDesc_lbm_2eproto();
  friend void protobuf_AssignDesc_lbm_2eproto();
  friend void protobuf_ShutdownFile_lbm_2eproto();

  void InitAsDefaultInstance();
  static BaseappInitProgress* default_instance_;
};
// ===================================================================


// ===================================================================

// RegisterPendingAccount

// optional string loginName = 1;
inline bool RegisterPendingAccount::has_loginname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegisterPendingAccount::set_has_loginname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegisterPendingAccount::clear_has_loginname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegisterPendingAccount::clear_loginname() {
  if (loginname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_->clear();
  }
  clear_has_loginname();
}
inline const ::std::string& RegisterPendingAccount::loginname() const {
  // @@protoc_insertion_point(field_get:login_basemgr.RegisterPendingAccount.loginName)
  return *loginname_;
}
inline void RegisterPendingAccount::set_loginname(const ::std::string& value) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(value);
  // @@protoc_insertion_point(field_set:login_basemgr.RegisterPendingAccount.loginName)
}
inline void RegisterPendingAccount::set_loginname(const char* value) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(value);
  // @@protoc_insertion_point(field_set_char:login_basemgr.RegisterPendingAccount.loginName)
}
inline void RegisterPendingAccount::set_loginname(const char* value, size_t size) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:login_basemgr.RegisterPendingAccount.loginName)
}
inline ::std::string* RegisterPendingAccount::mutable_loginname() {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:login_basemgr.RegisterPendingAccount.loginName)
  return loginname_;
}
inline ::std::string* RegisterPendingAccount::release_loginname() {
  clear_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = loginname_;
    loginname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RegisterPendingAccount::set_allocated_loginname(::std::string* loginname) {
  if (loginname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete loginname_;
  }
  if (loginname) {
    set_has_loginname();
    loginname_ = loginname;
  } else {
    clear_has_loginname();
    loginname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:login_basemgr.RegisterPendingAccount.loginName)
}

// optional string accountName = 2;
inline bool RegisterPendingAccount::has_accountname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RegisterPendingAccount::set_has_accountname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RegisterPendingAccount::clear_has_accountname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RegisterPendingAccount::clear_accountname() {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_->clear();
  }
  clear_has_accountname();
}
inline const ::std::string& RegisterPendingAccount::accountname() const {
  // @@protoc_insertion_point(field_get:login_basemgr.RegisterPendingAccount.accountName)
  return *accountname_;
}
inline void RegisterPendingAccount::set_accountname(const ::std::string& value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set:login_basemgr.RegisterPendingAccount.accountName)
}
inline void RegisterPendingAccount::set_accountname(const char* value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set_char:login_basemgr.RegisterPendingAccount.accountName)
}
inline void RegisterPendingAccount::set_accountname(const char* value, size_t size) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:login_basemgr.RegisterPendingAccount.accountName)
}
inline ::std::string* RegisterPendingAccount::mutable_accountname() {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:login_basemgr.RegisterPendingAccount.accountName)
  return accountname_;
}
inline ::std::string* RegisterPendingAccount::release_accountname() {
  clear_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = accountname_;
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RegisterPendingAccount::set_allocated_accountname(::std::string* accountname) {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete accountname_;
  }
  if (accountname) {
    set_has_accountname();
    accountname_ = accountname;
  } else {
    clear_has_accountname();
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:login_basemgr.RegisterPendingAccount.accountName)
}

// optional string password = 3;
inline bool RegisterPendingAccount::has_password() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RegisterPendingAccount::set_has_password() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RegisterPendingAccount::clear_has_password() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RegisterPendingAccount::clear_password() {
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_->clear();
  }
  clear_has_password();
}
inline const ::std::string& RegisterPendingAccount::password() const {
  // @@protoc_insertion_point(field_get:login_basemgr.RegisterPendingAccount.password)
  return *password_;
}
inline void RegisterPendingAccount::set_password(const ::std::string& value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(value);
  // @@protoc_insertion_point(field_set:login_basemgr.RegisterPendingAccount.password)
}
inline void RegisterPendingAccount::set_password(const char* value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(value);
  // @@protoc_insertion_point(field_set_char:login_basemgr.RegisterPendingAccount.password)
}
inline void RegisterPendingAccount::set_password(const char* value, size_t size) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:login_basemgr.RegisterPendingAccount.password)
}
inline ::std::string* RegisterPendingAccount::mutable_password() {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:login_basemgr.RegisterPendingAccount.password)
  return password_;
}
inline ::std::string* RegisterPendingAccount::release_password() {
  clear_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = password_;
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RegisterPendingAccount::set_allocated_password(::std::string* password) {
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete password_;
  }
  if (password) {
    set_has_password();
    password_ = password;
  } else {
    clear_has_password();
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:login_basemgr.RegisterPendingAccount.password)
}

// optional uint64 dbid = 4;
inline bool RegisterPendingAccount::has_dbid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RegisterPendingAccount::set_has_dbid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RegisterPendingAccount::clear_has_dbid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RegisterPendingAccount::clear_dbid() {
  dbid_ = GOOGLE_ULONGLONG(0);
  clear_has_dbid();
}
inline ::google::protobuf::uint64 RegisterPendingAccount::dbid() const {
  // @@protoc_insertion_point(field_get:login_basemgr.RegisterPendingAccount.dbid)
  return dbid_;
}
inline void RegisterPendingAccount::set_dbid(::google::protobuf::uint64 value) {
  set_has_dbid();
  dbid_ = value;
  // @@protoc_insertion_point(field_set:login_basemgr.RegisterPendingAccount.dbid)
}

// optional uint32 flags = 5;
inline bool RegisterPendingAccount::has_flags() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RegisterPendingAccount::set_has_flags() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RegisterPendingAccount::clear_has_flags() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RegisterPendingAccount::clear_flags() {
  flags_ = 0u;
  clear_has_flags();
}
inline ::google::protobuf::uint32 RegisterPendingAccount::flags() const {
  // @@protoc_insertion_point(field_get:login_basemgr.RegisterPendingAccount.flags)
  return flags_;
}
inline void RegisterPendingAccount::set_flags(::google::protobuf::uint32 value) {
  set_has_flags();
  flags_ = value;
  // @@protoc_insertion_point(field_set:login_basemgr.RegisterPendingAccount.flags)
}

// optional string extraData = 6;
inline bool RegisterPendingAccount::has_extradata() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RegisterPendingAccount::set_has_extradata() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RegisterPendingAccount::clear_has_extradata() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RegisterPendingAccount::clear_extradata() {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_->clear();
  }
  clear_has_extradata();
}
inline const ::std::string& RegisterPendingAccount::extradata() const {
  // @@protoc_insertion_point(field_get:login_basemgr.RegisterPendingAccount.extraData)
  return *extradata_;
}
inline void RegisterPendingAccount::set_extradata(const ::std::string& value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set:login_basemgr.RegisterPendingAccount.extraData)
}
inline void RegisterPendingAccount::set_extradata(const char* value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set_char:login_basemgr.RegisterPendingAccount.extraData)
}
inline void RegisterPendingAccount::set_extradata(const char* value, size_t size) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:login_basemgr.RegisterPendingAccount.extraData)
}
inline ::std::string* RegisterPendingAccount::mutable_extradata() {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:login_basemgr.RegisterPendingAccount.extraData)
  return extradata_;
}
inline ::std::string* RegisterPendingAccount::release_extradata() {
  clear_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = extradata_;
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RegisterPendingAccount::set_allocated_extradata(::std::string* extradata) {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extradata_;
  }
  if (extradata) {
    set_has_extradata();
    extradata_ = extradata;
  } else {
    clear_has_extradata();
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:login_basemgr.RegisterPendingAccount.extraData)
}

// -------------------------------------------------------------------

// RegisterPendingAccountEx

// optional uint64 componentID = 1;
inline bool RegisterPendingAccountEx::has_componentid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegisterPendingAccountEx::set_has_componentid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegisterPendingAccountEx::clear_has_componentid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegisterPendingAccountEx::clear_componentid() {
  componentid_ = GOOGLE_ULONGLONG(0);
  clear_has_componentid();
}
inline ::google::protobuf::uint64 RegisterPendingAccountEx::componentid() const {
  // @@protoc_insertion_point(field_get:login_basemgr.RegisterPendingAccountEx.componentID)
  return componentid_;
}
inline void RegisterPendingAccountEx::set_componentid(::google::protobuf::uint64 value) {
  set_has_componentid();
  componentid_ = value;
  // @@protoc_insertion_point(field_set:login_basemgr.RegisterPendingAccountEx.componentID)
}

// optional string loginName = 2;
inline bool RegisterPendingAccountEx::has_loginname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RegisterPendingAccountEx::set_has_loginname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RegisterPendingAccountEx::clear_has_loginname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RegisterPendingAccountEx::clear_loginname() {
  if (loginname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_->clear();
  }
  clear_has_loginname();
}
inline const ::std::string& RegisterPendingAccountEx::loginname() const {
  // @@protoc_insertion_point(field_get:login_basemgr.RegisterPendingAccountEx.loginName)
  return *loginname_;
}
inline void RegisterPendingAccountEx::set_loginname(const ::std::string& value) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(value);
  // @@protoc_insertion_point(field_set:login_basemgr.RegisterPendingAccountEx.loginName)
}
inline void RegisterPendingAccountEx::set_loginname(const char* value) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(value);
  // @@protoc_insertion_point(field_set_char:login_basemgr.RegisterPendingAccountEx.loginName)
}
inline void RegisterPendingAccountEx::set_loginname(const char* value, size_t size) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:login_basemgr.RegisterPendingAccountEx.loginName)
}
inline ::std::string* RegisterPendingAccountEx::mutable_loginname() {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:login_basemgr.RegisterPendingAccountEx.loginName)
  return loginname_;
}
inline ::std::string* RegisterPendingAccountEx::release_loginname() {
  clear_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = loginname_;
    loginname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RegisterPendingAccountEx::set_allocated_loginname(::std::string* loginname) {
  if (loginname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete loginname_;
  }
  if (loginname) {
    set_has_loginname();
    loginname_ = loginname;
  } else {
    clear_has_loginname();
    loginname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:login_basemgr.RegisterPendingAccountEx.loginName)
}

// optional string accountName = 3;
inline bool RegisterPendingAccountEx::has_accountname() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RegisterPendingAccountEx::set_has_accountname() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RegisterPendingAccountEx::clear_has_accountname() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RegisterPendingAccountEx::clear_accountname() {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_->clear();
  }
  clear_has_accountname();
}
inline const ::std::string& RegisterPendingAccountEx::accountname() const {
  // @@protoc_insertion_point(field_get:login_basemgr.RegisterPendingAccountEx.accountName)
  return *accountname_;
}
inline void RegisterPendingAccountEx::set_accountname(const ::std::string& value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set:login_basemgr.RegisterPendingAccountEx.accountName)
}
inline void RegisterPendingAccountEx::set_accountname(const char* value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set_char:login_basemgr.RegisterPendingAccountEx.accountName)
}
inline void RegisterPendingAccountEx::set_accountname(const char* value, size_t size) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:login_basemgr.RegisterPendingAccountEx.accountName)
}
inline ::std::string* RegisterPendingAccountEx::mutable_accountname() {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:login_basemgr.RegisterPendingAccountEx.accountName)
  return accountname_;
}
inline ::std::string* RegisterPendingAccountEx::release_accountname() {
  clear_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = accountname_;
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RegisterPendingAccountEx::set_allocated_accountname(::std::string* accountname) {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete accountname_;
  }
  if (accountname) {
    set_has_accountname();
    accountname_ = accountname;
  } else {
    clear_has_accountname();
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:login_basemgr.RegisterPendingAccountEx.accountName)
}

// optional string password = 4;
inline bool RegisterPendingAccountEx::has_password() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RegisterPendingAccountEx::set_has_password() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RegisterPendingAccountEx::clear_has_password() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RegisterPendingAccountEx::clear_password() {
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_->clear();
  }
  clear_has_password();
}
inline const ::std::string& RegisterPendingAccountEx::password() const {
  // @@protoc_insertion_point(field_get:login_basemgr.RegisterPendingAccountEx.password)
  return *password_;
}
inline void RegisterPendingAccountEx::set_password(const ::std::string& value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(value);
  // @@protoc_insertion_point(field_set:login_basemgr.RegisterPendingAccountEx.password)
}
inline void RegisterPendingAccountEx::set_password(const char* value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(value);
  // @@protoc_insertion_point(field_set_char:login_basemgr.RegisterPendingAccountEx.password)
}
inline void RegisterPendingAccountEx::set_password(const char* value, size_t size) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:login_basemgr.RegisterPendingAccountEx.password)
}
inline ::std::string* RegisterPendingAccountEx::mutable_password() {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:login_basemgr.RegisterPendingAccountEx.password)
  return password_;
}
inline ::std::string* RegisterPendingAccountEx::release_password() {
  clear_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = password_;
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RegisterPendingAccountEx::set_allocated_password(::std::string* password) {
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete password_;
  }
  if (password) {
    set_has_password();
    password_ = password;
  } else {
    clear_has_password();
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:login_basemgr.RegisterPendingAccountEx.password)
}

// optional int32 entityID = 5;
inline bool RegisterPendingAccountEx::has_entityid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RegisterPendingAccountEx::set_has_entityid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RegisterPendingAccountEx::clear_has_entityid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RegisterPendingAccountEx::clear_entityid() {
  entityid_ = 0;
  clear_has_entityid();
}
inline ::google::protobuf::int32 RegisterPendingAccountEx::entityid() const {
  // @@protoc_insertion_point(field_get:login_basemgr.RegisterPendingAccountEx.entityID)
  return entityid_;
}
inline void RegisterPendingAccountEx::set_entityid(::google::protobuf::int32 value) {
  set_has_entityid();
  entityid_ = value;
  // @@protoc_insertion_point(field_set:login_basemgr.RegisterPendingAccountEx.entityID)
}

// optional uint64 dbid = 6;
inline bool RegisterPendingAccountEx::has_dbid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RegisterPendingAccountEx::set_has_dbid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RegisterPendingAccountEx::clear_has_dbid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RegisterPendingAccountEx::clear_dbid() {
  dbid_ = GOOGLE_ULONGLONG(0);
  clear_has_dbid();
}
inline ::google::protobuf::uint64 RegisterPendingAccountEx::dbid() const {
  // @@protoc_insertion_point(field_get:login_basemgr.RegisterPendingAccountEx.dbid)
  return dbid_;
}
inline void RegisterPendingAccountEx::set_dbid(::google::protobuf::uint64 value) {
  set_has_dbid();
  dbid_ = value;
  // @@protoc_insertion_point(field_set:login_basemgr.RegisterPendingAccountEx.dbid)
}

// optional uint32 flags = 7;
inline bool RegisterPendingAccountEx::has_flags() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RegisterPendingAccountEx::set_has_flags() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RegisterPendingAccountEx::clear_has_flags() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RegisterPendingAccountEx::clear_flags() {
  flags_ = 0u;
  clear_has_flags();
}
inline ::google::protobuf::uint32 RegisterPendingAccountEx::flags() const {
  // @@protoc_insertion_point(field_get:login_basemgr.RegisterPendingAccountEx.flags)
  return flags_;
}
inline void RegisterPendingAccountEx::set_flags(::google::protobuf::uint32 value) {
  set_has_flags();
  flags_ = value;
  // @@protoc_insertion_point(field_set:login_basemgr.RegisterPendingAccountEx.flags)
}

// optional string extraData = 8;
inline bool RegisterPendingAccountEx::has_extradata() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RegisterPendingAccountEx::set_has_extradata() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RegisterPendingAccountEx::clear_has_extradata() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RegisterPendingAccountEx::clear_extradata() {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_->clear();
  }
  clear_has_extradata();
}
inline const ::std::string& RegisterPendingAccountEx::extradata() const {
  // @@protoc_insertion_point(field_get:login_basemgr.RegisterPendingAccountEx.extraData)
  return *extradata_;
}
inline void RegisterPendingAccountEx::set_extradata(const ::std::string& value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set:login_basemgr.RegisterPendingAccountEx.extraData)
}
inline void RegisterPendingAccountEx::set_extradata(const char* value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set_char:login_basemgr.RegisterPendingAccountEx.extraData)
}
inline void RegisterPendingAccountEx::set_extradata(const char* value, size_t size) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:login_basemgr.RegisterPendingAccountEx.extraData)
}
inline ::std::string* RegisterPendingAccountEx::mutable_extradata() {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:login_basemgr.RegisterPendingAccountEx.extraData)
  return extradata_;
}
inline ::std::string* RegisterPendingAccountEx::release_extradata() {
  clear_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = extradata_;
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RegisterPendingAccountEx::set_allocated_extradata(::std::string* extradata) {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extradata_;
  }
  if (extradata) {
    set_has_extradata();
    extradata_ = extradata;
  } else {
    clear_has_extradata();
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:login_basemgr.RegisterPendingAccountEx.extraData)
}

// -------------------------------------------------------------------

// LoginAccountQueryBaseappAddrFromBaseappmgr

// optional string loginName = 1;
inline bool LoginAccountQueryBaseappAddrFromBaseappmgr::has_loginname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_has_loginname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::clear_has_loginname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::clear_loginname() {
  if (loginname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_->clear();
  }
  clear_has_loginname();
}
inline const ::std::string& LoginAccountQueryBaseappAddrFromBaseappmgr::loginname() const {
  // @@protoc_insertion_point(field_get:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.loginName)
  return *loginname_;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_loginname(const ::std::string& value) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(value);
  // @@protoc_insertion_point(field_set:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.loginName)
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_loginname(const char* value) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(value);
  // @@protoc_insertion_point(field_set_char:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.loginName)
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_loginname(const char* value, size_t size) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.loginName)
}
inline ::std::string* LoginAccountQueryBaseappAddrFromBaseappmgr::mutable_loginname() {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.loginName)
  return loginname_;
}
inline ::std::string* LoginAccountQueryBaseappAddrFromBaseappmgr::release_loginname() {
  clear_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = loginname_;
    loginname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_allocated_loginname(::std::string* loginname) {
  if (loginname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete loginname_;
  }
  if (loginname) {
    set_has_loginname();
    loginname_ = loginname;
  } else {
    clear_has_loginname();
    loginname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.loginName)
}

// optional string accountName = 2;
inline bool LoginAccountQueryBaseappAddrFromBaseappmgr::has_accountname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_has_accountname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::clear_has_accountname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::clear_accountname() {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_->clear();
  }
  clear_has_accountname();
}
inline const ::std::string& LoginAccountQueryBaseappAddrFromBaseappmgr::accountname() const {
  // @@protoc_insertion_point(field_get:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.accountName)
  return *accountname_;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_accountname(const ::std::string& value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.accountName)
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_accountname(const char* value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set_char:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.accountName)
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_accountname(const char* value, size_t size) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.accountName)
}
inline ::std::string* LoginAccountQueryBaseappAddrFromBaseappmgr::mutable_accountname() {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.accountName)
  return accountname_;
}
inline ::std::string* LoginAccountQueryBaseappAddrFromBaseappmgr::release_accountname() {
  clear_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = accountname_;
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_allocated_accountname(::std::string* accountname) {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete accountname_;
  }
  if (accountname) {
    set_has_accountname();
    accountname_ = accountname;
  } else {
    clear_has_accountname();
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.accountName)
}

// optional string ip = 3;
inline bool LoginAccountQueryBaseappAddrFromBaseappmgr::has_ip() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_has_ip() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::clear_has_ip() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::clear_ip() {
  if (ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_->clear();
  }
  clear_has_ip();
}
inline const ::std::string& LoginAccountQueryBaseappAddrFromBaseappmgr::ip() const {
  // @@protoc_insertion_point(field_get:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.ip)
  return *ip_;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_ip(const ::std::string& value) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_ = new ::std::string;
  }
  ip_->assign(value);
  // @@protoc_insertion_point(field_set:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.ip)
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_ip(const char* value) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_ = new ::std::string;
  }
  ip_->assign(value);
  // @@protoc_insertion_point(field_set_char:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.ip)
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_ip(const char* value, size_t size) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_ = new ::std::string;
  }
  ip_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.ip)
}
inline ::std::string* LoginAccountQueryBaseappAddrFromBaseappmgr::mutable_ip() {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.ip)
  return ip_;
}
inline ::std::string* LoginAccountQueryBaseappAddrFromBaseappmgr::release_ip() {
  clear_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = ip_;
    ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_allocated_ip(::std::string* ip) {
  if (ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ip_;
  }
  if (ip) {
    set_has_ip();
    ip_ = ip;
  } else {
    clear_has_ip();
    ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.ip)
}

// optional uint32 port = 4;
inline bool LoginAccountQueryBaseappAddrFromBaseappmgr::has_port() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_has_port() {
  _has_bits_[0] |= 0x00000008u;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::clear_has_port() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::clear_port() {
  port_ = 0u;
  clear_has_port();
}
inline ::google::protobuf::uint32 LoginAccountQueryBaseappAddrFromBaseappmgr::port() const {
  // @@protoc_insertion_point(field_get:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.port)
  return port_;
}
inline void LoginAccountQueryBaseappAddrFromBaseappmgr::set_port(::google::protobuf::uint32 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:login_basemgr.LoginAccountQueryBaseappAddrFromBaseappmgr.port)
}

// -------------------------------------------------------------------

// BaseappInitProgress

// optional uint32 baseappsInitProgress = 1;
inline bool BaseappInitProgress::has_baseappsinitprogress() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BaseappInitProgress::set_has_baseappsinitprogress() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BaseappInitProgress::clear_has_baseappsinitprogress() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BaseappInitProgress::clear_baseappsinitprogress() {
  baseappsinitprogress_ = 0u;
  clear_has_baseappsinitprogress();
}
inline ::google::protobuf::uint32 BaseappInitProgress::baseappsinitprogress() const {
  // @@protoc_insertion_point(field_get:login_basemgr.BaseappInitProgress.baseappsInitProgress)
  return baseappsinitprogress_;
}
inline void BaseappInitProgress::set_baseappsinitprogress(::google::protobuf::uint32 value) {
  set_has_baseappsinitprogress();
  baseappsinitprogress_ = value;
  // @@protoc_insertion_point(field_set:login_basemgr.BaseappInitProgress.baseappsInitProgress)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace login_basemgr

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lbm_2eproto__INCLUDED
